# Generated by Django 4.2.5 on 2023-10-02 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 17, 42, 25, 359422, tzinfo=datetime.timezone.utc)),
        ),
    ]
