# Generated by Django 4.2.5 on 2023-09-22 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar_images/avatar.jpg', upload_to='MobiMarket/media/avatar_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 13, 48, 31, 465377, tzinfo=datetime.timezone.utc)),
        ),
    ]
