# Generated by Django 4.2.5 on 2023-10-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
        ('users', '0005_alter_user_date_of_birth'),
    ]

    operations = [
    ]
