# Generated by Django 4.2.5 on 2023-09-23 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_code_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('verification_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 1, 34, 26, 468994, tzinfo=datetime.timezone.utc)),
        ),
    ]
