# Generated by Django 4.2.5 on 2023-09-23 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 1, 40, 49, 843876, tzinfo=datetime.timezone.utc)),
        ),
    ]
