# Generated by Django 4.2.5 on 2023-09-23 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 2, 30, 53, 95101, tzinfo=datetime.timezone.utc)),
        ),
    ]
