# Generated by Django 4.2.5 on 2023-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeproduct',
            options={'verbose_name': 'Лайки', 'verbose_name_plural': 'Лайк'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='product_image/images.jpeg', upload_to='MobiMarket/media/product_image', verbose_name='Фото товара'),
        ),
    ]
