# Generated by Django 4.2.5 on 2023-10-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_short_description_alter_product_available_and_more'),
        ('products', '0002_remove_product_available_product_short_description_and_more'),
    ]

    operations = [
    ]
